---

# Since Ansible is supposed to be idempotent, we'll use _devstack_deployed_ file
# to indicate that devstack has already been successfully deployed so that
# the next Ansible provision run will do reconfiguration only.
- name: devstack | main | Check {{ devstack_dest }}/_devstack_deployed_ exist
  stat:
    path: "{{ devstack_dest }}/_devstack_deployed_"
  register: devstack_deployed_stat_result

- name: devstack | main | Deploy devstack
  include: _deploy_devstack.yml
  when: devstack_deployed_stat_result.stat.exists == false

- name: devstack | main | Create {{ devstack_dest }}/_deployed_
  file:
    path: "{{ devstack_dest }}/_devstack_deployed_"
    state: touch

