---
# Since Ansible is supposed to be idempotent, we'll use _glance_configured_
# file to indicate that glance has already been successfully configured
# so that the next Ansible provision run will skip this step.
- name: glance | main | Check {{ devstack_dest }}/_glance_configured_ exist
  stat:
    path: "{{ devstack_dest }}/_glance_configured_"
  register: glance_configured_stat_result

- name: glance | main | Configure Glance
  include: _configure_glance.yml
  when: glance_configured_stat_result.stat.exists == false

- name: glance | main | Create {{ devstack_dest }}/_glance_configured_
  file:
    path: "{{ devstack_dest }}/_glance_configured_"
    state: touch
