---

- set_fact:
    ssl_server_san: IP:{{ host_ip }}
  when: host_ip is defined and not host_ip == ""

- name: keystone | _configure_server_cert | Generate private key
  include_role:
    name: pki
    tasks_from: generate_private_key
  vars:
    key_type: "{{ server_ssl_key_type }}"
    file_owner: wwwrun
    file_group: www
    file_mode: 0600
    key_size: "{{ server_ssl_key_size }}"
    key_file: "{{ server_ssl_private_key_file }}"

- name: keystone | _configure_server_cert | Generate cert request (CSR)
  include_role:
    name: pki
    tasks_from: generate_server_cert_req
  vars:
    key_file: "{{ server_ssl_private_key_file }}"

- name: keystone | _configure_server_cert | Generate server certificate
  include_role:
    name: pki
    tasks_from: issue_server_cert
  vars:
    server_cert_file: "{{ server_ssl_cert_file }}"

- name: keystone | _configure_server_cert | Copy CA certificates
  include_role:
    name: pki
    tasks_from: copy_ca_certs_chain
  vars:
    file_owner: root
    file_group: root
    file_mode: 0644
    ca_certs_file: "{{ server_ssl_ca_file }}"

