---
# Since Ansible is supposed to be idempotent, we'll use _keystone_configured_
# file to indicate that keystone has already been successfully configured
# so that the next Ansible provision run will skip this step.
- name: keystone | main | Check {{ devstack_dest }}/_keystone_configured_ exist
  stat:
    path: "{{ devstack_dest }}/_keystone_configured_"
  register: keystone_configured_stat_result

- name: keystone | main | Install Apache2 mode_auth_openidc
  become: yes
  zypper:
    name: ['apache2-mod_auth_openidc']
    state: latest
  when: enable_oidc | bool

- name: keystone | main | Enable auth_openidc Apache2 module
  become: yes
  apache2_module:
    name: auth_openidc
    state: present
  when: enable_oidc | bool

- name: keystone | main | Enable auth_kerb Apache2 module
  become: yes
  apache2_module:
    name: auth_kerb
    state: present
  when: enable_kerberos_external_auth | bool

- name: keystone | main | Restart Apache2
  become: yes
  systemd:
    name: apache2
    state: restarted
  when: enable_oidc | bool

- name: keystone | main | Configure Keystone
  include: _configure_keystone.yml
  when: keystone_configured_stat_result.stat.exists == false

- name: keystone | main | Create {{ devstack_dest }}/_keystone_configured_
  file:
    path: "{{ devstack_dest }}/_keystone_configured_"
    state: touch

