---
# Since Ansible is supposed to be idempotent, we'll use _horizon_configured_
# file to indicate that horizon has already been successfully configured
# so that the next Ansible provision run will skip this step.
- name: horizon | main | Check {{ devstack_dest }}/_horizon_configured_ exist
  stat:
    path: "{{ devstack_dest }}/_horizon_configured_"
  register: horizon_configured_stat_result

- name: horizon | main | Configure Horizon
  include: _configure_horizon.yml
  when: horizon_configured_stat_result.stat.exists == false

- name: horizon | main | Create {{ devstack_dest }}/_horizon_configured_
  file:
    path: "{{ devstack_dest }}/_horizon_configured_"
    state: touch
