---

- set_fact:
    csr_file: "{{ intermediate_ca_csr_dir }}/{{ ssl_server_host_name }}_{{ timestamp }}.csr"

- name: pki | issue_server_certificate | Create {{ intermediate_ca_conf_file }}
  become: yes
  template:
    src: intermediate-ca.conf.j2
    dest: "{{ intermediate_ca_conf_file }}"
  delegate_to: "{{ groups.pki[0] }}"

- name: pki | issue_server_certificate | Issue certificate for {{ csr_file }}
  become: yes
  command: |
    openssl ca
      -config "{{ intermediate_ca_conf_file }}"
      -extensions server_cert
      -days 3650
      -notext
      -md sha256
      -in "{{ csr_file }}"
      -batch
  register: server_cert_pem
  delegate_to: "{{ groups.pki[0] }}"

- name: pki | issue_server_certificate | Create {{ server_cert_file }}
  become: yes
  copy:
    content: "{{ server_cert_pem.stdout }}"
    dest: "{{ server_cert_file }}"
    force: no
