---

- set_fact:
    csr_file: "{{ intermediate_ca_csr_dir }}/{{ user_domain_name }}_{{user_name}}_{{ timestamp }}.csr"

- name: pki | issue_user_cert | Issue certificate for {{ csr_file }}
  become: yes
  command: |
    openssl ca
      -config "{{ intermediate_ca_conf_file }}"
      -extensions user_cert
      -days 3650
      -notext
      -md sha256
      -in "{{ csr_file }}"
      -batch
  register: user_cert_pem
  delegate_to: "{{ groups.pki[0] }}"

- name: pki | issue_user_cert | Create {{ user_cert_file }}
  become: yes
  copy:
    content: "{{ user_cert_pem.stdout }}"
    dest: "{{ user_cert_file }}"
    force: no
