---
# NOTE(gyee) These task works on OpenSuSE/SLES only

#- name: Install build essentials
#  become: yes
#  zypper:
#    name: pattern:devel_basis
#    state: latest

- name: Install essential packages
  become: yes
  zypper:
    name: ['git', 'gnutls', 'python-pip', 'python-devel', 'libvirt',
           'bridge-utils', 'hostname']
    state: latest

- name: Install/upgrade setuptools
  become: yes
  pip:
    name: ['pip', 'setuptools']
    state: latest

# don't do this in production
- name: Disable SSL verify for git
  shell: >
    git config --global "{{ item.name }}" "{{ item.value }}"
  with_items:
    - {"name": "http.sslVerify", "value": "false"}

- name: Add IP address of all hosts to all hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].host_ip }} {{ item }}"
    state: present
  when: hostvars[item].ansible_host is defined and
        hostvars[item].host_ip is defined
  with_items: "{{ groups.all }}"
